
POST http://localhost:3001/api/persons/
content-type:  application/json

{
    "name": "Lettuce",
    "number": "99887700"
}

###

GET http://localhost:3001/api/persons/60eeef01e8b135428055dca6

###

GET http://localhost:3001/info